apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnest-backend-config
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend

data:
  PORT: "5000"
  NODE_ENV: "production"
  FRONTEND_URL: "http://72.144.100.232"
