apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnest-backend-config
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend

data:
  PORT: {{ .Values.backend.config.port | quote }}
  NODE_ENV: {{ .Values.backend.config.nodeEnv | quote }}
  FRONTEND_URL: {{ .Values.backend.config.frontendUrl | quote }}