apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopnest-backend
  labels:
    release: monitoring
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shopnest-backend
      app.kubernetes.io/part-of: shopnest
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s