apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: shopnest-backend
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend

spec:
  provider: azure

  secretObjects:
    - secretName: shopnest-backend-secret
      type: Opaque
      data:
        - objectName: CLOUDINARY-API-KEY
          key: CLOUDINARY_API_KEY

        - objectName: CLOUDINARY-API-SECRET
          key: CLOUDINARY_API_SECRET

        - objectName: CLOUDINARY-CLOUD-NAME
          key: CLOUDINARY_CLOUD_NAME

        - objectName: GMAIL-PASS
          key: GMAIL_PASS

        - objectName: GMAIL-USER
          key: GMAIL_USER

        - objectName: JWT-SECRET
          key: JWT_SECRET

        - objectName: MONGO-URI
          key: MONGO_URI

        - objectName: RAZORPAY-KEY-ID
          key: RAZORPAY_KEY_ID

        - objectName: RAZORPAY-KEY-SECRET
          key: RAZORPAY_KEY_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "443a5b48-6ea7-4187-9010-e98644a85da6"

    keyvaultName: "shopnest-kv"
    tenantId: "25ea82b6-dfae-45a3-8712-f925d1b3397d"

    objects: |
      array:
        - |
          objectName: CLOUDINARY-API-KEY
          objectType: secret
        - |
          objectName: CLOUDINARY-API-SECRET
          objectType: secret
        - |
          objectName: CLOUDINARY-CLOUD-NAME
          objectType: secret
        - |
          objectName: GMAIL-PASS
          objectType: secret
        - |
          objectName: GMAIL-USER
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: RAZORPAY-KEY-ID
          objectType: secret
        - |
          objectName: RAZORPAY-KEY-SECRET
          objectType: secret
