apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopnest-ingress
  labels:
    app.kubernetes.io/part-of: shopnest

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}

          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: shopnest-frontend
                port:
                  number: {{ .Values.frontend.port }}