{{- if eq .Values.secrets.provider "azure" }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClassName }}
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend

spec:
  provider: azure

  secretObjects:
    - secretName: shopnest-backend-secret
      type: Opaque
      data:
        - objectName: CLOUDINARY-API-KEY
          key: CLOUDINARY_API_KEY

        - objectName: CLOUDINARY-API-SECRET
          key: CLOUDINARY_API_SECRET

        - objectName: CLOUDINARY-CLOUD-NAME
          key: CLOUDINARY_CLOUD_NAME

        - objectName: GMAIL-PASS
          key: GMAIL_PASS

        - objectName: GMAIL-USER
          key: GMAIL_USER

        - objectName: JWT-SECRET
          key: JWT_SECRET

        - objectName: MONGO-URI
          key: MONGO_URI

        - objectName: RAZORPAY-KEY-ID
          key: RAZORPAY_KEY_ID

        - objectName: RAZORPAY-KEY-SECRET
          key: RAZORPAY_KEY_SECRET

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.azure.userAssignedIdentityID | quote }}

    keyvaultName: {{ .Values.secrets.azure.keyvaultName | quote }}
    tenantId: {{ .Values.secrets.azure.tenantId | quote }}

    objects: |
      array:
        - |
          objectName: CLOUDINARY-API-KEY
          objectType: secret
        - |
          objectName: CLOUDINARY-API-SECRET
          objectType: secret
        - |
          objectName: CLOUDINARY-CLOUD-NAME
          objectType: secret
        - |
          objectName: GMAIL-PASS
          objectType: secret
        - |
          objectName: GMAIL-USER
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: RAZORPAY-KEY-ID
          objectType: secret
        - |
          objectName: RAZORPAY-KEY-SECRET
          objectType: secret

{{- end }}