backend:
  image:
    repository: ""
    tag: v2

  replicas: 2
  port: 5000

  config:
    port: "5000"
    nodeEnv: "production"
    frontendUrl: ""

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image:
    repository: ""
    tag: v2

  replicas: 2
  port: 8080

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

  razorpayKeyId: ""

secrets:
  enabled: false
  providerClassName: shopnest-backend