backend:
  image:
    repository: shopnestdevacr.azurecr.io/shopnest-backend
    tag: v2

  config:
    port: "5000"
    nodeEnv: "production"
    frontendUrl: ""

frontend:
  image:
    repository: shopnestdevacr.azurecr.io/shopnest-frontend
    tag: v2

  razorpayKeyId: "rzp_test_TOpPJJoN5F2yHB"

secrets:
  enabled: true
  providerClassName: shopnest-backend

  azure:
    userAssignedIdentityID: "1d640bd5-93f7-49d2-9461-feb7fe31aadd"
    keyvaultName: "shopnest-dev-kv2"
    tenantId: "e1e8e860-fa83-475d-ab45-170185504741"