apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnest-backend-config
  labels:
    {{- include "shopnest.labels" (dict "component" "backend") | nindent 4 }}

data:
  PORT: {{ .Values.backend.config.port | quote }}
  NODE_ENV: {{ .Values.backend.config.nodeEnv | quote }}
  FRONTEND_URL: {{ .Values.backend.config.frontendUrl | quote }}