{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClassName }}
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend

spec:
  provider: {{ .Values.cloud.provider }}

  secretObjects:
    - secretName: {{ .Values.secrets.k8sSecretName }}
      type: Opaque
      data:
        {{- range .Values.secrets.items }}
        - objectName: {{ .name }}
          key: {{ .key }}
        {{- end }}

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "{{ .Values.workloadIdentity.clientId }}"
    keyvaultName: "{{ .Values.secrets.azure.keyvaultName }}"
    tenantId: "{{ .Values.secrets.azure.tenantId }}"

    objects: |
      array:
        {{- range .Values.secrets.items }}
        - |
          objectName: {{ .name }}
          objectType: secret
        {{- end }}
{{- end }}
