{{- if .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
{{- end }}