apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "shopnest.labels" (dict "component" "backend") | nindent 4 }}

spec:
  selector:
    {{- include "shopnest.selectorLabels" (dict "component" "backend") | nindent 4 }}

  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      name: http

  type: ClusterIP