apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopnest-backend
  labels:
    app: shopnest-backend
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: shopnest-backend
  template:
    metadata:
      labels:
        app: shopnest-backend
        app.kubernetes.io/name: shopnest-backend
        app.kubernetes.io/part-of: shopnest
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: shopnestacr.azurecr.io/shopnest-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: shopnest-backend-secret
            - configMapRef:
                name: shopnest-backend-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5