apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: shopnest-backend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: backend
spec:
  selector:
    app: shopnest-backend
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP