apiVersion: v1
kind: ConfigMap
metadata:
  name: shopnest-frontend-config
  labels:
    app.kubernetes.io/name: shopnest-frontend
    app.kubernetes.io/part-of: shopnest
    app.kubernetes.io/component: frontend

data:
  config.js: |
    window.RUNTIME_CONFIG = {
      RAZORPAY_KEY_ID: "{{ .Values.frontend.razorpayKeyId }}"
    };