{{- if .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shopnest-frontend
  labels:
    {{- include "shopnest.labels" (dict "component" "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "shopnest.selectorLabels" (dict "component" "frontend") | nindent 6 }}
{{- end }}
