apiVersion: v1
kind: Service
metadata:
  name: shopnest-frontend
  labels:
    {{- include "shopnest.labels" (dict "component" "frontend") | nindent 4 }}

spec:
  selector:
    {{- include "shopnest.selectorLabels" (dict "component" "frontend") | nindent 4 }}

  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      name: http

  type: ClusterIP